// dados.js
const medicamentos = [
    { nome: "Paracetamol", posologia: "1 comprimido a cada 6 horas" },
    { nome: "Ibuprofeno", posologia: "1 comprimido a cada 8 horas" },
    { nome: "Amoxicilina", posologia: "1 cápsula a cada 12 horas" },
    { nome: "Dipirona", posologia: "1 comprimido a cada 6 horas" },
    { nome: "Ranitidina", posologia: "1 comprimido a cada 12 horas" },
    { nome: "Loratoquina", posologia: "1 comprimido ao dia" },
    { nome: "Metformina", posologia: "1 comprimido durante as refeições" },
    { nome: "Cetirizina", posologia: "1 comprimido ao dia" },
    { nome: "Omeprazol", posologia: "1 cápsula pela manhã" },
    { nome: "Simvastatina", posologia: "1 comprimido à noite" },
    { nome: "Atenolol", posologia: "1 comprimido ao dia" },
    { nome: "Furosemida", posologia: "1 comprimido pela manhã" },
    { nome: "Fluoxetina", posologia: "1 cápsula ao dia" },
    { nome: "Ciprofloxacino", posologia: "1 comprimido a cada 12 horas" },
    { nome: "Clonazepam", posologia: "1 comprimido à noite" },
    { nome: "Metoclopramida", posologia: "1 comprimido a cada 8 horas" },
    { nome: "Salmeterol", posologia: "1 inalação a cada 12 horas" },
    { nome: "Insulina", posologia: "Administrar conforme prescrição médica" },
    { nome: "Levodopa", posologia: "1 comprimido a cada 8 horas" },
    { nome: "Dexametasona", posologia: "1 comprimido a cada 24 horas" },
    { nome: "Metformina", posologia: "1 comprimido durante as refeições" },
    { nome: "Cetirizina", posologia: "1 comprimido ao dia" },
    { nome: "Omeprazol", posologia: "1 cápsula pela manhã" },
    { nome: "Simvastatina", posologia: "1 comprimido à noite"},
    { nome: "Ranitidina", posologia: "1 comprimido a cada 12 horas" },
    { nome: "Loratadina", posologia: "1 comprimido ao dia" },
    { nome: "Metformina", posologia: "1 comprimido durante as refeições" },
    { nome: "Cetirizina", posologia: "1 comprimido ao dia" },
    { nome: "Omeprazol", posologia: "1 cápsula pela manhã" },
    { nome: "Simvastatina", posologia: "1 comprimido à noite" },
    { nome: "Atenolol", posologia: "1 comprimido ao dia" },
    { nome: "Furosemida", posologia: "1 comprimido pela manhã" },
    { nome: "Fluoxetina", posologia: "1 cápsula ao dia" },
    { nome: "Ciprofloxacino", posologia: "1 comprimido a cada 12 horas" },
    { nome: "Clonazepam", posologia: "1 comprimido à noite" },
    { nome: "Metoclopramida", posologia: "1 comprimido a cada 8 horas" },
    { nome: "Salmeterol", posologia: "1 inalação a cada 12 horas" },
    { nome: "Insulina", posologia: "Administrar conforme prescrição médica" },
    { nome: "Levodopa", posologia: "1 comprimido a cada 8 horas" },
    { nome: "Dexametasona", posologia: "1 comprimido a cada 24 horas" },
    { nome: "Tramadol", posologia: "1 comprimido a cada 12 horas" },
    { nome: "Sertralina", posologia: "1 comprimido ao dia" },
    { nome: "Espironolactona", posologia: "1 comprimido pela manhã" },
    { nome: "Montelucaste", posologia: "1 comprimido ao dia" },
    { nome: "Levotiroxina", posologia: "1 comprimido ao acordar" },
    { nome: "Acarbose", posologia: "1 comprimido durante as refeições" },
    { nome: "Clopidogrel", posologia: "1 comprimido ao dia" },
    { nome: "Lansoprazol", posologia: "1 cápsula pela manhã" },
    { nome: "Gabapentina", posologia: "1 comprimido a cada 8 horas" },
    { nome: "Bromoprida", posologia: "1 comprimido a cada 8 horas" },
    { nome: "Fenitoína", posologia: "1 comprimido a cada 12 horas" },
    { nome: "Citalopram", posologia: "1 comprimido ao dia" },
    { nome: "Diclofenaco", posologia: "1 comprimido a cada 8 horas" },
    { nome: "Metoprolol", posologia: "1 comprimido ao dia" },
    { nome: "Nimesulida", posologia: "1 comprimido a cada 12 horas" },
    { nome: "Fexofenadina", posologia: "1 comprimido ao dia" },
    { nome: "Tamsulosina", posologia: "1 cápsula ao dia" },
    { nome: "Propranolol", posologia: "1 comprimido ao dia" },
    { nome: "Ciclosporina", posologia: "Administrar conforme prescrição médica" },
    { nome: "Sildenafila", posologia: "1 comprimido 30 minutos antes da relação sexual" },
    { nome: "Tadalafila", posologia: "1 comprimido ao dia ou 30 minutos antes da relação sexual" },
    // Adicione mais medicamentos conforme necessário
];

